services:
  trainer:
    image: asdfry/train-llm:20231109
    runtime: nvidia
    volumes:
      - /gpfs/jsh:/root/mnt
    command: ["/bin/bash", "-c", "/usr/sbin/sshd -p 1041 && sleep infinity"]
    ports:
      - 1040:1040
      - 1041:1041
    shm_size: 1GB
    network_mode: host
    privileged: true
