services:
  trainer:
    image: asdfry/train-llm:20231201
    volumes:
      - /home/jsh/volume:/root/mnt
    command: ["/bin/bash", "-c", "/usr/sbin/sshd -p 1041 && sleep infinity"]
    ports:
      - 1041:1041
    shm_size: 1GB
    # network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            # device_ids: ['0', '1', '2', '3']
            capabilities: [gpu]
