apiVersion: v1
kind: Pod
metadata:
  labels:
    ten1010.io/creator-name: jsh
  name: worker
  namespace: common
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - /usr/sbin/sshd -p 1041 && sleep infinity
    image: asdfry/text-generation:accelerate-20230830
    name: app
    ports:
    - containerPort: 1041
      hostPort: 1041
      protocol: TCP
    resources:
      limits:
        ten1010.io/gpu-tesla-t4: "2"
      requests:
        ten1010.io/gpu-tesla-t4: "2"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /root/pretrained-models
      name: pretrained-models
    - mountPath: /dev/shm
      name: shmdir
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: k8s-node-3
  volumes:
  - name: pretrained-models
    persistentVolumeClaim:
      claimName: jsh-pvc
  - name: shmdir
    emptyDir:
      medium: Memory
      sizeLimit: 256M
