version: "3.6"

services:

  master:
    image: asdfry/text-generation:horovod-${version}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "-c", "/usr/sbin/sshd && sleep infinity"]
    volumes:
      - ./logs:/root/logs:rw
      - ./hostfile:/root/hostfile:rw
      - ./config:/root/.ssh/config:rw
      - ./pretrained-models:/root/pretrained-models:ro
    # ports:
    #   - 1041:22
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu]

  # worker-1:
  #   image: asdfry/text-generation:horovod-${version}
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["/bin/bash", "-c", "/usr/sbin/sshd && sleep infinity"]
  #   volumes:
  #     - ./pretrained-models:/root/pretrained-models:ro
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['2', '3']
  #           capabilities: [gpu]

  # worker-2:
  #   image: asdfry/text-generation:horovod-${version}
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["/bin/bash", "-c", "/usr/sbin/sshd && sleep infinity"]
  #   volumes:
  #     - ./pretrained-models:/root/pretrained-models:ro
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['4', '5']
  #           capabilities: [gpu]

  # worker-3:
  #   image: asdfry/text-generation:horovod-${version}
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["/bin/bash", "-c", "/usr/sbin/sshd && sleep infinity"]
  #   volumes:
  #     - ./pretrained-models:/root/pretrained-models:ro
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['6', '7']
  #           capabilities: [gpu]
