version: "3.6"

services:

  api:
    image: asdfry/infer-llm:20231109
    runtime: nvidia
    volumes:
      - /gpfs/jsh:/root/mnt:ro
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 1047:8000
    environment:
      - MODEL_NAME=Llama-2-7b-chat-hf
